### ISSUE TITLE
OpenCanopy Graphical Glitches & EFI Information

### ISSUE THREAD

**Issue by TechProgenitor** [kingo132/a51m-r2-5700m-hackintosh#7]
Hi Kingo, thank you for your recent efforts on the EFI!
I see that you’re using OpenCanopy, and was wondering if you’ve dealt with this graphical glitching before?

![IMG_0763](https://user-images.githubusercontent.com/89800154/180663899-94d6a871-a698-4501-9c48-b1fae9a4f334.jpg)

I’m able to fix it in the config.plist file by enabling DirectGopRendering, but this makes the boot loader render slower (vertical lines move slowly across the screen sometimes).

If your boot loader is displaying boot entries glitch-free/latency-free, could you please send me your BIOS settings?
We might have different parameters enabled/disabled.

Otherwise, I’ve purchased the same 4K display/connector as you, and could try installing it sometime which might fix this.
(Perhaps you could fill me in on the details regarding upgrading the display if it comes to this.)

Finally I’ve got a lot of information to tell you:

VoodooI2C.kext in your latest config.plist file is placed before VoodooGPIO.kext. It needs to go after VoodooGPIO.kext for the trackpad to work properly. (Don’t ask me why.)

My internal SATA drive requires CtlnaAHCIPort.kext in order to boot.
Please consider adding this kext to the EFI/config.plist if it doesn’t conflict with anything.

I use SSDT-EC-USBX-LAPTOP.aml instead of SSDT-EC-USBX-DESKTOP.aml in order to have proper battery indication and sleep when closing the lid which leads me to believe that there’s a bug somewhere in the ASL code for SSDT-EC-USBX-DESKTOP.aml. If necessary for proper performance (because this laptop has a desktop CPU), perhaps a hybrid can be created out of SSDT-EC-USBX-LAPTOP.aml and SSDT-EC-USBX-DESKTOP.aml?

I got a boot chime working, but it makes the boot loader take slightly longer to load.
At the top left of the screen just before the boot entries splash screen, this text pops up:

![IMG_0768](https://user-images.githubusercontent.com/89800154/180664028-207b6172-28fc-494e-a411-f5836f85fe76.PNG)

I wonder if this is related to the delay though it didn’t remove the debug text when enabling it.
(for aesthetics, this debug text can be removed by making Target=0)

If you're interested in adding a startup chime, here's the latest config.plist on GitHub with the necessary modifications:
I've also included a startup chime from the HomePod which I've remastered to sound good on our speakers.
[a51m-R2 Working Startup Chime.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/9176592/a51m-R2.Working.Startup.Chime.zip)
If you decide to create your own chime, it has to be a 16 bit 48000 HZ .wav file.

**Comment by kingo132** [comment]
Hey, really appreciate your recommendation. Most of your solution is to the problem that I have encountered before.

One of my friends, who also has a51mr2 and the 1080p@144hz display, has that boot glitch as well. But I didn't encounter that. Maybe because I have long replaced the display to 4k120hz before I upgrade to Monterey.

For the panel upgrading, you should be careful operating the cable since they are fragile. Moreover, use tweezers to remove that specific adhesive tape underneath the old panel before you lift it. Then, use the same kind of adhesive tape (which can be bought on eBay or Amazon) to adhere the new panel to the case. Before you do that, make sure the new panel is carefully aligned in the center of the frame because my panel is shifted a bit left, and I noticed it until everything was assembled. It's kind of frustrating.
Here is my BIOS setting.

![IMG_1706](https://user-images.githubusercontent.com/46492291/180915437-e163c299-db1b-42bf-839c-db2b92d4565c.jpeg)
![IMG_1709](https://user-images.githubusercontent.com/46492291/180915469-293e6349-140b-4fee-a2c7-eddc68914cc2.jpeg)
![IMG_1708](https://user-images.githubusercontent.com/46492291/180915454-07a189cc-ef04-495d-b1a7-1b8a121babf5.jpeg)
![IMG_1707](https://user-images.githubusercontent.com/46492291/180915461-c3410ec4-16b3-4c19-a3fe-96fbcdcc6402.jpeg)

I suppose you are right. SSDT-EC-USBX-LAPTOP.aml is more suitable. I guess there's no need to make a hybrid because they are two different strategies when considering desktop and laptop. https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-fix.html

The sequence of VoodooI2C works. Thanks! But that touchpad is kind of useless since it will interrupt the typing and does not has gestures, so I'm disabling it by default.

I added CtlnaAHCIPort.kext and there's no problem so far.

The boot chime works pretty well, but it slows the boot process a bit. However, it sounds more interesting after adding that function.

**Comment by TechProgenitor** [comment]
Hi Kingo, I’m glad that you mentioned your friend to me because now I’m strongly convinced that an EDID override will fix the glitches. I’ve done this before in Clover with my old Toshiba laptop to make the bootloader 1080p, but I don’t know if OpenCore even lets you inject an EDID into OpenCanopy.
Regardless I’ll compare my BIOS settings to see if changing a setting fixes things.
If that doesn’t work and I can’t inject an EDID, I’m quite certain that the display upgrade (which I want to do anyway) will fix this.

Regarding the display upgrade, I’m not sure what kind of adhesive tape I need to purchase to install the new display.
Perhaps you could send me a link of the tape that you used?

Finally, I was wondering why some of my BIOS settings didn’t look similar to yours, then Windows 10 force updated my BIOS today from revision 1.10.0 to 1.17.0 (it's disgusting that Windows can even do this in my opinion). This new BIOS allowed me to turn off SupportAssist which was driving me crazy though (idk thank you Microsoft)!

**Comment by kingo132** [comment]
Hi, my friend fixed that boot glitch by enabling that DirectGopRendering option.

That glue strip is something like this. It has a pull tab that tweezers can drag to remove the whole glue strip conveniently without damaging the LCD panel.
https://www.ebay.com/itm/393963058195
https://www.ebay.com/itm/283955459732
